[package]
name = "gateway"
version = "0.0.0"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
models = { path = "../models" }
usecases = { path = "../usecases" }
persistence = { path = "../persistence", features = ["postgres"] }
